backend/og/atomCore/urls.py
from django.urls import path

from .views.contact import *
from.utils import HealthCheckHandler

app_name = 'atomCore'

urlpatterns = [
    path('contact/', ContactHandler.as_view(), name='contact'),
    path('health/', HealthCheckHandler.as_view(), name='health_check'),
]

backend/og/atomProject/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.sitemaps.views import sitemap
#from .sitemaps import PostSitemap
from django.http import HttpResponse

#sitemaps = {
#    'static': PostSitemap,
#}

urlpatterns = [
    path('v1/', include('atomAPIv1.urls')),
    path('admin/', admin.site.urls),
    #path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='sitemap'),
    #url(r'^robots.txt$', lambda r: HttpResponse("User-agent: *\nDisallow: \nSitemap:https://bookwatch.jp/sitemap.xml", content_type="text/plain")),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/og/common/models.py
from django.db import models

# Create your models here.

backend/og/common/views.py
from django.shortcuts import render

# Create your views here.

backend/og/templates/common/base.html
<!DOCTYPE html>
<html lang="ja">
    {% load static %}
    {% bootstrap_css %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>{% block title %}{{ title }}{% endblock %}</title>
    <link rel="icon" type="image/x-icon" href="{% static 'asset/img/logo/favicon.svg' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/remodal/1.0.5/remodal.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/remodal/1.0.5/remodal-default-theme.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css">
    <link rel="stylesheet" type="text/css" href='{% static "asset/css/style.css" %}'>
    <link rel="stylesheet" type="text/css" href='{% static "asset/css/remodal/remodal.css" %}'>
    <link rel="stylesheet" type="text/css" href='{% static "asset/css/remodal/remodal-default-theme.css" %}'>
    {% block extracss %}{% endblock %}
</head>
<body>
    {% block content %}{% endblock %}
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="  crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/infinite-scroll@4/dist/infinite-scroll.pkgd.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jscroll/2.4.1/jquery.jscroll.js" integrity="sha512-AgWDJkG13uHcgm8NoCl1qcTk5gml73x2ZAkIe7ljOgT/pRdYYLbcGG1cY8GDOEQt/se3kdBf8t6IaAl8XFPOiw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
    <script src='{% static "asset/js/remodal/remodal.js" %}'></script>
    <script src='{% static "asset/js/custom-slick.js" %}'></script>
    {% block extrajs %}{% endblock %}
</body>

</html>

backend/og/templates/common/footer.html
{% load static %}
<!--
<footer class="">
    <div class="container">
        <div class="row mt-5">
            <div class="col-4">
                <p>
                    {{ service_name }} 
                </p>
                <p>
                    Address<br>
                    <small>
                        〒641-0004<br>
                    和歌山県和歌山市和田905-3<br>
                    080-3476-6225
                    </small>
                </p>
            </div>
            <div class="col-4">
                <p>
                    Contents
                </p>
                <table width="100%">
                    <tr height="35">
                        <td class="">
                            <a href="">
                                Home
                            </a>
                        </td>
                    </tr>
                    <tr height="35">
                        <td class="">
                            <a href="">
                                ご利用案内
                            </a>
                        </td>
                    </tr>
                    <tr height="35">
                        <td class="">
                            <a href="">
                                ご利用料金
                            </a>
                        </td>
                    </tr>
                    <tr height="35">
                        <td class="">
                            <a href="">
                                施設概要
                            </a>
                        </td>
                    </tr>
                    <tr height="35">
                        <td class="">
                            <a href="">
                                予約方法
                            </a>
                        </td>
                    </tr>
                    {% if site_master.instagram %}
                    <tr height="35">
                        <td class="">
                            <a href="">
                                instagram
                            </a>
                        </td>
                    </tr>
                    {% endif %}
                    <tr height="35">
                        <td class="">
                            <a href="">
                                お問い合わせ
                            </a>
                        </td>
                    </tr>
                </table>
            </div>

        </div>

    </div>
    <div class="text-center m-3">
        <p class="tazugane-light m-1">Copyright © {{ service_name }} All Rights Reserved.</p>
    </div>
</footer>
-->

backend/og/templates/common/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light bg-white mt-2 ml-3 mr-3 pt-3 pb-3 rounded-lg shadow fixed-top">
    <a href="" class="navbar-brand ml-2">
        <img src="{% static 'asset/img/logo/code-college-logo-black.svg' %}" style="width:160px;" class="" alt="">
    </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="ナビゲーションの切替">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse bg-white m-0" id="navbar">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item ">
                <a class="nav-link tazugane-heavy ml-2 mr-2" href="{% url 'atomCore:index' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link tazugane-heavy ml-2 mr-2" href="{% url 'atomCore:guide' %}">ご利用案内</a>
            </li>
            <li class="nav-item">
                <a class="nav-link tazugane-heavy ml-2 mr-2" href="{% url 'atomCore:price' %}">ご利用料金</a>
            </li>
            <li class="nav-item">
                <a class="nav-link tazugane-heavy ml-2 mr-2" href="{% url 'atomCore:facility' %}">施設概要</a>
            </li>
            <li class="nav-item">
                <a class="nav-link tazugane-heavy ml-2 mr-2" href="{% url 'atomCore:reserve' %}">予約方法</a>
            </li>
            {% if site_master.instagram %}
            <li class="nav-item">
                <a class="nav-link tazugane-heavy ml-2 mr-2" href="">instagram</a>
            </li>
            {% endif %}
            <li class="nav-item">
                <a class="nav-link tazugane-heavy ml-2 mr-2" href="{% url 'atomCore:contact' %}">お問い合わせ</a>
            </li>
        </ul>
      </div>
  </nav>